CREATE TABLE IF NOT EXISTS public.chat_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id text NOT NULL REFERENCES public.chat_sessions(session_id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])),
    content text NOT NULL,
    sources jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS chat_messages_session_created_idx
    ON public.chat_messages(session_id, created_at DESC);

ALTER TABLE public.chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_messages ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.touch_chat_session()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE public.chat_sessions
    SET updated_at = now()
    WHERE session_id = NEW.session_id;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS chat_messages_touch_session ON public.chat_messages;
CREATE TRIGGER chat_messages_touch_session
AFTER INSERT ON public.chat_messages
FOR EACH ROW EXECUTE FUNCTION public.touch_chat_session();
